name: test
description: test 


publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0' 
  flutter: "3.27.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  add_2_calendar: 3.0.1
  android_intent_plus: 5.2.2
  app_settings: 5.1.1
  appcheck: 1.5.3 
  archive: 3.6.1
  async: 2.11.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  collection: 1.19.0
  cupertino_icons: 1.0.8
  device_info_plus: 11.2.1
  email_validator: 3.0.0
  equatable: 2.0.7
  firebase_core: 3.10.1
  firebase_crashlytics: 4.3.1
  firebase_messaging: 15.2.1
  flutter_cache_manager: 3.4.1
  flutter_local_notifications: 18.0.1
  flutter_map: 5.0.0 
  flutter_map_animations: 0.4.1 
  flutter_markdown: 0.7.5
  flutter_secure_storage: 9.2.3
  flutter_svg: 2.0.17
  focus_detector: 2.0.1
  geolocator: 13.0.2
  http: 1.3.0
  in_app_review: 2.0.10
  intl: 0.19.0
  intl_utils: 2.8.8
  latlong2: 0.9.1 
  m_login_sdk: 1.3.0
  map_launcher: 3.5.0 
  package_info_plus: 8.1.3
  pay: 2.0.0
  phone_numbers_parser: 9.0.3
  provider: 6.1.2
  qr_flutter: 4.1.0
  rive: 0.13.20
  rxdart: 0.28.0
  screen_brightness: 2.1.1
  scroll_to_index: 3.0.1
  share_plus: 10.1.4
  shared_preferences: 2.4.0
  shimmer: 3.0.0
  smooth_page_indicator: 1.2.0+3
  svg_path_parser: 1.1.2
  swipe_refresh: 1.1.2
  timeago: 3.7.0 
  timezone: 0.10.0
  url_launcher: 6.3.1
  uuid: 4.5.1
  vector_math: 2.1.4
  xml: 6.5.0
  yaml: 3.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.15
  flutter_gen_runner: 5.8.0
  mockito: 5.4.5
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  main_locale: en
  enabled: true
  class_name: S

  localizely:
    project_id: 00000000-0000-0000-0000-000000000000
    download_empty_as: empty

flutter_gen:
  output: lib/generated/
  line_length: 80

  assets:
    exclude:
      - assets/image/**

  integrations:
    flutter_svg: true
    rive: true
