---
name: Renovate Bot

on  :
  workflow_dispatch:

jobs:
  renovate-bot:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Run Renovate Bot
        uses: renovatebot/github-action@v40.2.0
        with:
          configurationFile: tmp.json
          token: x-access-token:${{ secrets.USER_GIT_TOKEN }}
          #renovate-version: full
        env:
          LOG_LEVEL: debug
